import org.springframework.web.filter.ShallowEtagHeaderFilter.HttpStreamingAwareContentCachingResponseWrapper;
public class FunctionUse5286 {
public void funcUse() {
HttpStreamingAwareContentCachingResponseWrapper httpstreamingawarecontentcachingresponsewrapper = new HttpStreamingAwareContentCachingResponseWrapper();
httpstreamingawarecontentcachingresponsewrapper.useRawResponse();
}
}