import org.springframework.web.bind.UnsatisfiedServletRequestParameterException;
public class FunctionUse4195 {
public void funcUse() {
UnsatisfiedServletRequestParameterException unsatisfiedservletrequestparameterexception = new UnsatisfiedServletRequestParameterException();
unsatisfiedservletrequestparameterexception.requestParameterMapToString(null);
}
}